---
- name: 'Am I a Banana or not?'
  hosts: localhost
  connection: local
  vars:
    fruit: banana
  tasks:
    - name: run banana
      command: echo "I am a Banana"
      when: fruit == "banana"
    - name: run bana
      command: echo "I am not a Banana"
      when: fruit != "banana"